### ISSUE TITLE
'Namespace' object has no attribute 'train_s_list'

### ISSUE THREAD

**Issue by darkdante2209** [anicolson/DeepXi#25]
Sir, when i put data on the folder set, than run file "run.m", i got these errors, how could i fix it?

/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Creating test_x list, as no pickle file exists...
The test_x list has a total of 1 entries.
Finding sample statistics...
Traceback (most recent call last):
  File "deepxi.py", line 37, in <module>
    args = get_stats(args.data_path, args, config)
  File "lib/dev/sample_stats.py", line 28, in get_stats
    random.shuffle(args.train_s_list) # shuffle list.
AttributeError: 'Namespace' object has no attribute 'train_s_list'

**Comment by anicolson** [comment]
Are you trying to train? You are going to have to give more information about where you put your data

**Comment by darkdante2209** [comment]
Yes I am going to train, i chose some file wav from nonspeech and qut-noise and put it in set/train-noise and val-noise, than i chose some file flac from LibriSpeech to put it in set/train-clean-speech and val-clean-speech, than i run training script like you guide

**Comment by anicolson** [comment]
I have not tested the run.m file with training. Are you able to run:


python3 deepxi.py --train 1 --ver 'ANY_NAME' --gpu 0



________________________________

**Comment by darkdante2209** [comment]
yes, i ran that's script and it sent me the error i posted

**Comment by anicolson** [comment]
I just tested with run.m and --train 1, and it works successfully. Have you modified deepxi.py or train.py in any way?
________________________________

**Comment by anicolson** [comment]
Can you replace the ```add_args``` function in args.py with this please, and show me the output:
````
def add_args(args, modulation=False):

	## DEPENDANT OPTIONS
	args.model_path = args.model_path + '/' + args.ver # model save path.
	args.train_s_path = args.set_path + '/train_clean_speech' # path to the clean speech training set.
	args.train_d_path = args.set_path + '/train_noise' # path to the noise training set.
	args.val_s_path = args.set_path + '/val_clean_speech' # path to the clean speech validation set.
	args.val_d_path = args.set_path + '/val_noise' # path to the noise validation set.
	args.out_path = args.out_path + '/' + args.ver + '/' + 'e' + str(args.epoch) # output path.
	args.N_w = int(args.f_s*args.T_w*0.001) # window length (samples).
	args.N_s = int(args.f_s*args.T_s*0.001) # window shift (samples).
	args.NFFT = int(pow(2, np.ceil(np.log2(args.N_w)))) # number of DFT components.

	## DATASETS
	if args.train: ## TRAINING AND VALIDATION CLEAN SPEECH AND NOISE SET
		args.train_s_list = Batch_list(args.train_s_path, 'clean_speech_' + args.set_path.rsplit('/', 1)[-1], args.data_path) # clean speech training list.
		args.train_d_list = Batch_list(args.train_d_path, 'noise_' + args.set_path.rsplit('/', 1)[-1], args.data_path) # noise training list.
		if not os.path.exists(args.model_path): os.makedirs(args.model_path) # make model path directory.
		args.val_s, args.val_s_len, args.val_snr, _ = Batch(args.val_s_path,  
			list(range(args.min_snr, args.max_snr + 1))) # clean validation waveforms and lengths.
		args.val_d, args.val_d_len, _, _ = Batch(args.val_d_path, 
			list(range(args.min_snr, args.max_snr + 1))) # noise validation waveforms and lengths.
		args.train_steps=int(np.ceil(len(args.train_s_list)/args.mbatch_size))
		args.val_steps=int(np.ceil(args.val_s.shape[0]/args.mbatch_size))

		print(len(args.train_s_list))
		print(len(args.train_d_list))
		print(args.val_s.shape)
		print(args.val_d.shape)

		exit()

	## INFERENCE
	# if args.infer: args.test_x, args.test_x_len, args.test_snr, args.test_fnames = Batch(args.test_x_path, '*', []) # noisy speech test waveforms and lengths.
	if args.infer: args.test_x_list = Batch_list(args.test_x_path, 'test_x', args.data_path, make_new=True)
	return args

````

Another option is that you can use ````data/stats.p```` from the repository.

**Comment by darkdante2209** [comment]
No sir, i didn't modify anything, just clone the code from github and do what you said in README, after i modified in a `add_args` as you said, it gave me these errors:

```
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Creating clean_speech_set list, as no pickle file exists...
The clean_speech_set list has a total of 64 entries.
Creating noise_set list, as no pickle file exists...
The noise_set list has a total of 64 entries.
Traceback (most recent call last):
  File "deepxi.py", line 31, in <module>
    args = add_args(args)
  File "lib/dev/args.py", line 37, in add_args
    list(range(args.min_snr, args.max_snr + 1))) # clean validation waveforms and lengths.
  File "lib/dev/se_batch.py", line 153, in Batch
    wav_np[i,:len(wav)] = wav # add waveform to numpy array.
ValueError: could not broadcast input array from shape (100995200,2) into shape (100995200)

```

**Comment by anicolson** [comment]
some of the .wav files that you are using are stereo. You must convert them to single-channel.
________________________________

**Comment by darkdante2209** [comment]
Sorry sir i don't understand, you mean it's had to be 16kHz? could i use .flac files from LibriSpeech or it has to be .wav files?

**Comment by anicolson** [comment]
I am not talking about the sampling frequency or the coding format, I am talking about the number of channels of your audio. Deep Xi is made for single-channel audio. You must convert all multi-channel recordings to single-channel.
________________________________

**Comment by darkdante2209** [comment]
Thank you so much sir, and how about the .flac file?

**Comment by anicolson** [comment]
.flac is fine

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by darkdante2209** [comment]
While i changed the data, it's coming this: 
```
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Creating clean_speech_set list, as no pickle file exists...
The clean_speech_set list has a total of 60 entries.
Creating noise_set list, as no pickle file exists...
The noise_set list has a total of 60 entries.
60
60
(60, 175633)
(60, 175633)

```
But when i ran Inference script: 
```
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/Users/minhhuypham/venv/DeepXi/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Creating test_x list, as no pickle file exists...
The test_x list has a total of 1 entries.
Finding sample statistics...
Traceback (most recent call last):
  File "deepxi.py", line 37, in <module>
    args = get_stats(args.data_path, args, config)
  File "lib/dev/sample_stats.py", line 28, in get_stats
    random.shuffle(args.train_s_list) # shuffle list.
AttributeError: 'Namespace' object has no attribute 'train_s_list'

```

**Comment by anicolson** [comment]
This is because training hasn't been completed. stats.p is created during training. I have updated the code to catch these problems:

````
## GET STATISTICS OF SAMPLE
def get_stats(stats_path, args, config):
	if os.path.exists(stats_path + '/stats.p'):
		print('Loading sample statistics from pickle file...')
		with open(stats_path + '/stats.p', 'rb') as f:
			args.stats = pickle.load(f)
		return args
	elif args.infer:
		raise ValueError('You have not completed training (no stats.p file exsists). In the Deep Xi github repository, data/stats.p is available.')
	else:
		print('Finding sample statistics...')
		random.shuffle(args.train_s_list) # shuffle list.
		s_sample, s_sample_seq_len = batch.Clean_mbatch(args.train_s_list, 
			args.sample_size, 0, args.sample_size) # generate mini-batch of clean training waveforms.
		d_sample, d_sample_seq_len = batch.Noise_mbatch(args.train_d_list, 
			args.sample_size, s_sample_seq_len) # generate mini-batch of noise training waveforms.
		snr_sample = np.random.randint(args.min_snr, args.max_snr + 1, args.sample_size) # generate mini-batch of SNR levels.
		s_ph = tf.placeholder(tf.int16, shape=[None, None], name='s_ph') # clean speech placeholder.
		d_ph = tf.placeholder(tf.int16, shape=[None, None], name='d_ph') # noise placeholder.
		s_len_ph = tf.placeholder(tf.int32, shape=[None], name='s_len_ph') # clean speech sequence length placeholder.
		d_len_ph = tf.placeholder(tf.int32, shape=[None], name='d_len_ph') # noise sequence length placeholder.
		snr_ph = tf.placeholder(tf.float32, shape=[None], name='snr_ph') # SNR placeholder.
		analysis = polar.target_xi(s_ph, d_ph, s_len_ph, d_len_ph, snr_ph, args.N_w, args.N_s, args.NFFT, args.f_s)
		sample_graph = analysis[0]
		samples = []
		with tf.Session(config=config) as sess:
			for i in tqdm(range(s_sample.shape[0])):
				sample = sess.run(sample_graph, feed_dict={s_ph: [s_sample[i]], d_ph: [d_sample[i]], s_len_ph: [s_sample_seq_len[i]], 
					d_len_ph: [d_sample_seq_len[i]], snr_ph: [snr_sample[i]]}) # sample of training set.
				samples.append(sample)
		samples = np.vstack(samples)
		if len(samples.shape) != 2: ValueError('Incorrect shape for sample.')
		args.stats = {'mu_hat': np.mean(samples, axis=0), 'sigma_hat': np.std(samples, axis=0)}
		if not os.path.exists(stats_path): os.makedirs(stats_path) # make directory.
		with open(stats_path + '/stats.p', 'wb') as f: 		
			pickle.dump(args.stats, f)
		spio.savemat(stats_path + '/stats.m', mdict={'mu_hat': args.stats['mu_hat'], 'sigma_hat': args.stats['sigma_hat']})
		print('Sample statistics saved to pickle file.')
	return args
````

Please update your args.py and sample_stats.py to the current versions.

**Comment by darkdante2209** [comment]
Thank you sir, do i need to care about this warning?
`FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.`

**Comment by anicolson** [comment]
no need to worry about that
________________________________

**Comment by darkdante2209** [comment]
Just a little problem sir, how could i know that the training is completed? i just see the terminal command finish with 
```
The noise_set list has a total of 60 entries.
60
60
(60, 175633)
(60, 175633)
```

**Comment by anicolson** [comment]
You have to change args.py to the same that is on the github repository

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by darkdante2209** [comment]
yes, i just pulled your code from github

**Comment by darkdante2209** [comment]
I just updated the code from your git and now these errors coming 
```
Creating noise_set list, as no pickle file exists...
The noise_set list has a total of 6 entries.
Loading sample statistics from pickle file...
Preparing graph...
Training...
Traceback (most recent call last):
  File "deepxi.py", line 43, in <module>
    if args.train: train(sess, net, args)
  File "lib/dev/train.py", line 33, in train
    if args.mbatch_size > epoch_size: raise ValueError('Error: mini-batch size is greater than the epoch size.')
ValueError: Error: mini-batch size is greater than the epoch size.

```

**Comment by anicolson** [comment]
The error is pretty simple to fix. Your mini-batch size is greater than your batch size ( the number of clean speech files). Either increase your batch size, or decrease the mini-batch size.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by darkdante2209** [comment]
I fixed it, but now:
```
Finding sample statistics...
Traceback (most recent call last):
  File "deepxi.py", line 37, in <module>
    args = get_stats(args.data_path, args, config)
  File "lib/dev/sample_stats.py", line 34, in get_stats
    args.sample_size, s_sample_seq_len) # generate mini-batch of noise training waveforms.
  File "lib/dev/se_batch.py", line 95, in Noise_mbatch
    mbatch_list = random.sample(noise_list, mbatch_size) # get mini-batch list from training list.
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/random.py", line 321, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative

```

**Comment by anicolson** [comment]
the mini-batch size is greater than the number of noise files. You need to understand that a large number of clean speech and noise files are required to successfully train a neural network.
________________________________

**Comment by darkdante2209** [comment]
Okay sir, sorry for alot of question but I'm just a newbie here

**Comment by anicolson** [comment]
That’s OK, happy to answer more questions

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by darkdante2209** [comment]
About the validation set sir, you noted that: Identical filenames for the clean speech and noise must be placed in 'val_clean_speech' and 'val_noise', with the SNR at the end of the filename. As an example:
'./val_clean_speech/198_19-198-0003_Machinery17_15dB.wav' contains the clean speech, and './val_noise/198_19-198-0003_Machinery17_15dB.wav' contains the noise at the same length. They will be mixed together at the SNR level specified in the filename.
So i have to create a validation dataset myself that a pair of file clean and noise speech has same duration and same name?

**Comment by darkdante2209** [comment]
While i cloned again your code from github, setting than just inference with my test file, but it clear both speech and noise in my test file like this, why? 
[](https://raw.githubusercontent.com/darkdante2209/noise-reduce/master/assets/download%20(2).wav)
[](https://raw.githubusercontent.com/darkdante2209/noise-reduce/master/assets/download%20(1).wav)

**Comment by anicolson** [comment]
Sorry, I do not follow, could you clarify what you said. Also, the .wav files will not play.

**Comment by darkdante2209** [comment]
Sorry for wrong question, i really didn't understand about the validation dataset you mean, Do i have to create a validation dataset myself that a pair of file clean and noise speech has same duration and same name?

**Comment by anicolson** [comment]
Yes

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by darkdante2209** [comment]
Still couldn't train with my validation dataset sir, did you upload your dataset on cloud or some where? I need some  reference

**Comment by anicolson** [comment]
https://ieee-dataport.org/open-access/deep-xi-training-set

https://ieee-dataport.org/open-access/deep-xi-test-set

**Comment by darkdante2209** [comment]
In your test set, i see the the file in folder "test noise" and "test clean speech" is same, right?

**Comment by anicolson** [comment]
Those are just used to create the test_noisy_speech.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by darkdante2209** [comment]
When i ran with you val dataset, i got there errors sir!
`Creating clean_speech_set list, as no pickle file exists...
The clean_speech_set list has a total of 28424 entries.
Creating noise_set list, as no pickle file exists...
The noise_set list has a total of 108 entries.
Finding sample statistics...
Traceback (most recent call last):
  File "deepxi.py", line 37, in <module>
    args = get_stats(args.data_path, args, config)
  File "lib/dev/sample_stats.py", line 34, in get_stats
    args.sample_size, s_sample_seq_len) # generate mini-batch of noise training waveforms.
  File "lib/dev/se_batch.py", line 95, in Noise_mbatch
    mbatch_list = random.sample(noise_list, mbatch_size) # get mini-batch list from training list.
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/random.py", line 321, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative
`

**Comment by anicolson** [comment]
The sample size is 1000 an you are using 108 noise sources. The sample size is thus too large, or you need more noise files.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
