### ISSUE TITLE
Error loading pretrain model during inference

### ISSUE THREAD

**Issue by zhouyong64** [anicolson/DeepXi#45]
The running environment is Cuda 10.1, tensorflow 2.2. The error message is as follows:

Total params: 1,949,953
Trainable params: 1,949,953
Non-trainable params: 0
__________________________________________________________________________________________________
Traceback (most recent call last):
  File "/root/sw/env4py36_deepxi/lib/python3.6/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 95, in NewCheckpointReader
    return CheckpointReader(compat.as_bytes(filepattern))
RuntimeError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for model/resnet-1.1n/epoch-179/variables/variables

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 92, in <module>
    saved_data_path=args.saved_data_path,
  File "/root/sw/DeepXi-master/deepxi/model.py", line 269, in infer
    self.model.load_weights(model_path + '/epoch-' + str(e-1) +'/variables/variables' )
  File "/root/sw/env4py36_deepxi/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 250, in load_weights
    return super(Model, self).load_weights(filepath, by_name, skip_mismatch)
  File "/root/sw/env4py36_deepxi/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1231, in load_weights
    py_checkpoint_reader.NewCheckpointReader(filepath)
  File "/root/sw/env4py36_deepxi/lib/python3.6/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 99, in NewCheckpointReader
    error_translator(e)
  File "/root/sw/env4py36_deepxi/lib/python3.6/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 35, in error_translator
    raise errors_impl.NotFoundError(None, None, error_message)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for model/resnet-1.1n/epoch-179/variables/variables

**Comment by anicolson** [comment]
Hi, I am fixing this issue now, I will update you when it has been fixed.

**Comment by anicolson** [comment]
There was an issue with the files in the `model` directory. New files have been uploaded to the repository, which has fixed the problem.

Hope this helps,
Aaron.

**Comment by zhouyong64** [comment]
Thanks.
